## Part II. Programming

In [1]:
from __future__ import division
from pylab import *

def lu(A):
    """LU decomposition of A without pivoting (Doolittle's method)."""
    n = shape(A)[0]
    L = eye(n)
    U = zeros([n,n])
    for k in range(n):
        U[k,k:] = A[k,k:] - dot(L[k,:k], U[:k,k:])        
        L[k+1:,k] = (A[k+1:,k] - dot(L[k+1:,:k], U[:k,k]))/U[k,k]
    return L, U

### Problem 2
a. What is the smallest k ∈ N where this problem occurs for ε = 10^−k?

k = 16, problem occurs: 

In [2]:
def test(eps):
    A = array([[eps,1],[1,1]])
    [L, U] = lu(A)
    return dot(L, U)

In [3]:
# when k = 15, the result is still correct
test(1e-15)

array([[  1.00000000e-15,   1.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00]])

In [4]:
# when k = 16, problem occurs
test(1e-16) 

array([[  1.00000000e-16,   1.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00]])

b. Verify that this does not occur for the pivoted matrix P A =
using the value of  obtained in part a.

In [5]:
A = array([[1e-16,1],[1,1]])
# swapping A's rows
PA = A[[1,0]]
# LU decomposition
L, U = lu(PA)
# check 
dot(L, U)

array([[  1.00000000e+00,   1.00000000e+00],
       [  1.00000000e-16,   1.00000000e+00]])

The result is correct this time

### Problem 3
In hw4.py, the function uSolve solves the upper triangular system ```U x = b``` using back substitution. (The only tricky part here is iterating backwards, which is done using the reversed function. As with the function lu, notice the use of dot to compute the sum as a dot product.)
Similarly the function lSolve is meant to solve the lower triangular system ```Lx = b``` using forward substitution—but it is only partly implemented. Finish the implementation by replacing the dummy line
```
    x[i] = 0 # replace this line
```
in the main loop with the appropriate expression for ```x[i]```. (Do not assume that L is unit lower triangular.) To test your implementation, run the following commands and print your output:

In [6]:
def uSolve(U,b):
    """Solve an upper triangular system Ux = b by back substitution."""
    n = size(b)
    x = zeros(n)
    # the reversed() function lets you iterate backwards over a list
    for i in reversed(range(n)):      
        x[i] = (b[i] - dot(U[i,i+1:], x[i+1:]))/U[i,i]
    return x
    
def lSolve(L,b):
    """Solve a lower triangular system Lx = b by forward substitution."""
    n = size(b)
    x = zeros(n)
    for i in range(n):  
        # x[i] = 0 # replace this line
        x[i] = (b[i] - dot(L[i,:i+1],x[:i+1]))/L[i,i]  
    return x

In [7]:
seed(449)
L = tril(rand(3,3))
b = rand(3)
lSolve(L,b)

array([ 1.05480036,  0.3342922 , -1.98575009])

### Problem 4
Create a function luSolve(L,U,b) which solves the system LUx = b using forward and back substitution.

In [8]:
def luSolve(L, U, b):
    n = size(b)
    x = zeros(n)
    y = zeros(n)
    y = lSolve(L, b)
    x = uSolve(U, y)
    return x

In [9]:
seed(449)
A = rand(3,3)
b = rand(3)
L,U = lu(A)
luSolve(L,U,b)

array([-0.38645093,  0.60217606,  0.59442979])